got Puppet to run, and now getting the correct Hiera classes.
Next problem is one I hadn't thought of... this is going to be painful...

Error: Evaluation Error: Error while evaluating a Function Call, Unsupported platform: Archlinux/Archlinux at /etc/puppetlabs/code/environments/production/modules/ssh/manifests/params.pp:56:11 on node vagrant-arch

Looks like our version of saz/ssh doesn't support Puppet4. Let's just hope that it's really old.